"""Add Restaurant Partner models for SPEC3

Revision ID: 53999b354bf3
Revises: 68ae3863b721
Create Date: 2026-05-04 10:01:46.578569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53999b354bf3'
down_revision: Union[str, None] = '68ae3863b721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_offers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('offer_type', sa.Enum('FLAT', 'PERCENT', 'FREE_DELIVERY', 'BOGO', name='restaurant_offer_type_enum'), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('max_discount', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('min_order_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('usage_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('restaurant_offers', schema=None) as batch_op:
        batch_op.create_index('ix_restaurant_offers_restaurant_is_active', ['restaurant_id', 'is_active'], unique=False)

    op.create_table('restaurant_partners',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('owner_name', sa.String(length=200), nullable=False),
    sa.Column('business_type', sa.Enum('RESTAURANT', 'CLOUD_KITCHEN', 'BAKERY', 'CAFE', 'FOOD_TRUCK', name='business_type_enum'), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), server_default=sa.text('20.00'), nullable=False),
    sa.Column('wallet_balance', sa.Numeric(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=14, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('total_orders', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('bank_account_number', sa.String(length=20), nullable=True),
    sa.Column('bank_ifsc', sa.String(length=15), nullable=True),
    sa.Column('bank_account_name', sa.String(length=200), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('pan_number', sa.String(length=15), nullable=True),
    sa.Column('fssai_number', sa.String(length=20), nullable=False),
    sa.Column('fssai_expiry', sa.Date(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('restaurant_partners', schema=None) as batch_op:
        batch_op.create_index('ix_restaurant_partners_restaurant_id', ['restaurant_id'], unique=False)

    op.create_table('restaurant_timings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('opens_at', sa.Time(), nullable=False),
    sa.Column('closes_at', sa.Time(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'day_of_week', name='uq_restaurant_timing')
    )
    op.create_table('restaurant_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.Enum('FSSAI_LICENSE', 'GST_CERTIFICATE', 'PAN_CARD', 'BANK_CANCELLED_CHEQUE', 'OWNER_AADHAAR_FRONT', 'OWNER_AADHAAR_BACK', 'SHOP_ACT_LICENSE', 'PARTNERSHIP_DEED', 'MENU_PHOTO', 'RESTAURANT_PHOTO_FRONT', 'RESTAURANT_PHOTO_INTERIOR', name='restaurant_doc_type_enum'), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='restaurant_doc_status_enum'), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['restaurant_partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partner_id', 'doc_type', name='uq_restaurant_doc')
    )
    with op.batch_alter_table('restaurant_documents', schema=None) as batch_op:
        batch_op.create_index('ix_restaurant_documents_partner_id', ['partner_id'], unique=False)

    op.create_table('restaurant_payouts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('gross_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('commission_deducted', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_payout', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'PAID', 'FAILED', name='restaurant_payout_status_enum'), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('bank_account', sa.String(length=20), nullable=True),
    sa.Column('utr_number', sa.String(length=50), nullable=True),
    sa.Column('initiated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['restaurant_partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('restaurant_payouts', schema=None) as batch_op:
        batch_op.create_index('ix_restaurant_payouts_partner_status', ['partner_id', 'status'], unique=False)

    op.create_table('order_responses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('ACCEPTED', 'REJECTED', name='order_response_action_enum'), nullable=False),
    sa.Column('preparation_time', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=300), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preparation_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('restaurant_confirmed_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('restaurant_status')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('restaurant_confirmed_at')
        batch_op.drop_column('preparation_time')

    op.drop_table('order_responses')
    with op.batch_alter_table('restaurant_payouts', schema=None) as batch_op:
        batch_op.drop_index('ix_restaurant_payouts_partner_status')

    op.drop_table('restaurant_payouts')
    with op.batch_alter_table('restaurant_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_restaurant_documents_partner_id')

    op.drop_table('restaurant_documents')
    op.drop_table('restaurant_timings')
    with op.batch_alter_table('restaurant_partners', schema=None) as batch_op:
        batch_op.drop_index('ix_restaurant_partners_restaurant_id')

    op.drop_table('restaurant_partners')
    with op.batch_alter_table('restaurant_offers', schema=None) as batch_op:
        batch_op.drop_index('ix_restaurant_offers_restaurant_is_active')

    op.drop_table('restaurant_offers')
    # ### end Alembic commands ###
