"""create_delivery_partner_tables

Revision ID: 68ae3863b721
Revises: 7f0baf5f47e8
Create Date: 2026-04-25 14:07:09.062238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68ae3863b721'
down_revision: Union[str, None] = '7f0baf5f47e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incentive_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('DAILY_ORDERS', 'WEEKLY_ORDERS', 'PEAK_HOUR', 'RAIN_BONUS', 'CONSECUTIVE_DAYS', 'ACCEPTANCE_RATE', name='incentivetype'), nullable=False),
    sa.Column('threshold_value', sa.Integer(), nullable=True),
    sa.Column('bonus_amount', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_partners',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fe_id', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('vehicle_type', sa.String(length=20), nullable=True),
    sa.Column('vehicle_number', sa.String(length=20), nullable=True),
    sa.Column('vehicle_model', sa.String(length=100), nullable=True),
    sa.Column('is_online', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('current_latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('current_longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('last_location_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), server_default=sa.text('5.0'), nullable=False),
    sa.Column('total_ratings', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('acceptance_rate', sa.Numeric(precision=5, scale=2), server_default=sa.text('100.0'), nullable=False),
    sa.Column('completion_rate', sa.Numeric(precision=5, scale=2), server_default=sa.text('100.0'), nullable=False),
    sa.Column('total_deliveries', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_earnings', sa.Numeric(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('wallet_balance', sa.Numeric(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('referral_code', sa.String(length=20), nullable=True),
    sa.Column('referred_by', sa.UUID(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referred_by'], ['delivery_partners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_code')
    )
    with op.batch_alter_table('delivery_partners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_partners_fe_id'), ['fe_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_delivery_partners_user_id'), ['user_id'], unique=True)
        batch_op.create_index('ix_dp_city', ['city'], unique=False)
        batch_op.create_index('ix_dp_is_online_city', ['is_online', 'city'], unique=False)
        batch_op.create_index('ix_dp_location', ['current_latitude', 'current_longitude'], unique=False)

    op.create_table('kyc_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.Enum('AADHAAR_FRONT', 'AADHAAR_BACK', 'PAN_CARD', 'DRIVING_LICENSE_FRONT', 'DRIVING_LICENSE_BACK', 'VEHICLE_RC', 'VEHICLE_INSURANCE', 'BANK_PASSBOOK', 'PROFILE_PHOTO', 'POLICE_VERIFICATION', name='doctype'), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='docstatus'), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['delivery_partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partner_id', 'doc_type', name='uq_kyc_partner_doc_type')
    )
    with op.batch_alter_table('kyc_documents', schema=None) as batch_op:
        batch_op.create_index('ix_kyc_partner_id', ['partner_id'], unique=False)
        batch_op.create_index('ix_kyc_status', ['status'], unique=False)

    op.create_table('partner_locations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('speed_kmph', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('heading_degrees', sa.Integer(), nullable=True),
    sa.Column('accuracy_meters', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['delivery_partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partner_locations', schema=None) as batch_op:
        batch_op.create_index('ix_partner_locations_partner_recorded', ['partner_id', 'recorded_at'], unique=False)

    op.create_table('partner_shifts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('deliveries_in_shift', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('earnings_in_shift', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['delivery_partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partner_shifts', schema=None) as batch_op:
        batch_op.create_index('ix_partner_shifts_partner_started', ['partner_id', 'started_at'], unique=False)

    op.create_table('payouts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payout_period_start', sa.Date(), nullable=False),
    sa.Column('payout_period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'PAID', 'FAILED', name='payoutstatus'), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('bank_account', sa.String(length=20), nullable=True),
    sa.Column('utr_number', sa.String(length=50), nullable=True),
    sa.Column('initiated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['delivery_partners.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.create_index('ix_payouts_partner_status', ['partner_id', 'status'], unique=False)

    op.create_table('delivery_assignments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ASSIGNED', 'ACCEPTED', 'REJECTED', 'TIMED_OUT', 'REACHED_RESTAURANT', 'PICKED_UP', 'REACHED_CUSTOMER', 'DELIVERED', 'FAILED', name='assignmentstatus'), server_default=sa.text("'ASSIGNED'"), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=300), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=300), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('restaurant_latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('restaurant_longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('customer_latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('customer_longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('customer_address', sa.Text(), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('customer_phone', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['partner_id'], ['delivery_partners.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', name='uq_assignment_order')
    )
    with op.batch_alter_table('delivery_assignments', schema=None) as batch_op:
        batch_op.create_index('ix_da_order_id', ['order_id'], unique=False)
        batch_op.create_index('ix_da_partner_status', ['partner_id', 'status'], unique=False)

    op.create_table('partner_incentives',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('bonus_amount', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payout_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['delivery_partners.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payout_id'], ['payouts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['incentive_rules.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partner_incentives', schema=None) as batch_op:
        batch_op.create_index('ix_partner_incentives_partner_earned', ['partner_id', 'earned_at'], unique=False)

    op.create_table('delivery_otps',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('otp', sa.String(length=4), nullable=False),
    sa.Column('is_used', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['delivery_assignments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', name='uq_delivery_otp_assignment')
    )
    op.create_table('partner_earnings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('base_pay', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('distance_pay', sa.Numeric(precision=8, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('surge_pay', sa.Numeric(precision=8, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('incentive_pay', sa.Numeric(precision=8, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('tip_amount', sa.Numeric(precision=8, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('total_earned', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['delivery_assignments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['partner_id'], ['delivery_partners.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partner_earnings', schema=None) as batch_op:
        batch_op.create_index('ix_partner_earnings_partner_earned', ['partner_id', 'earned_at'], unique=False)

    op.create_table('support_tickets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('EARNINGS', 'ORDER_ISSUE', 'APP_BUG', 'PAYMENT', 'ACCOUNT', 'SAFETY', 'OTHER', name='ticketcategory'), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='ticketstatus'), server_default=sa.text("'OPEN'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['delivery_assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['partner_id'], ['delivery_partners.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.create_index('ix_support_tickets_partner_status', ['partner_id', 'status'], unique=False)

    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.drop_index('ix_support_tickets_partner_status')

    op.drop_table('support_tickets')
    with op.batch_alter_table('partner_earnings', schema=None) as batch_op:
        batch_op.drop_index('ix_partner_earnings_partner_earned')

    op.drop_table('partner_earnings')
    op.drop_table('delivery_otps')
    with op.batch_alter_table('partner_incentives', schema=None) as batch_op:
        batch_op.drop_index('ix_partner_incentives_partner_earned')

    op.drop_table('partner_incentives')
    with op.batch_alter_table('delivery_assignments', schema=None) as batch_op:
        batch_op.drop_index('ix_da_partner_status')
        batch_op.drop_index('ix_da_order_id')

    op.drop_table('delivery_assignments')
    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.drop_index('ix_payouts_partner_status')

    op.drop_table('payouts')
    with op.batch_alter_table('partner_shifts', schema=None) as batch_op:
        batch_op.drop_index('ix_partner_shifts_partner_started')

    op.drop_table('partner_shifts')
    with op.batch_alter_table('partner_locations', schema=None) as batch_op:
        batch_op.drop_index('ix_partner_locations_partner_recorded')

    op.drop_table('partner_locations')
    with op.batch_alter_table('kyc_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_kyc_status')
        batch_op.drop_index('ix_kyc_partner_id')

    op.drop_table('kyc_documents')
    with op.batch_alter_table('delivery_partners', schema=None) as batch_op:
        batch_op.drop_index('ix_dp_location')
        batch_op.drop_index('ix_dp_is_online_city')
        batch_op.drop_index('ix_dp_city')
        batch_op.drop_index(batch_op.f('ix_delivery_partners_user_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_partners_fe_id'))

    op.drop_table('delivery_partners')
    op.drop_table('incentive_rules')
    # ### end Alembic commands ###
